= Core Java Programming
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

== Java 8 New Features In Simple Way by DurgaSoft Durga

*Functional Interface*

* Predicate - take value, return boolean
** In Java 8, Predicate is a functional interface, which accepts an argument and returns a boolean.

----
Predicate <String> predicate1 = s->s.length()>3;
Predicate <String> predicate2 = s->s.length()<10;

System.out.println(predicate1.and(predicate2).test("a"));
System.out.println(predicate1.and(predicate2).test("abcd"));
System.out.println(predicate1.and(predicate2).test("abcdefghijklmno"));
----


* Consumer - take value, process it, does not return anything
** Consumer<T> is an in-built functional interface introduced in Java 8 in the java. ... Consumer can be used in all contexts where an object needs to be consumed,i.e. taken as input, and some operation is to be performed on the object without returning any result.

----
Consumer <String> displayConsumer = s->System.out.print(s);
displayConsumer.accept("Hello World");
----

* Function - take value, return value
** In Java 8, Function is a functional interface; it takes an argument (object of type T) and returns an object (object of type R). The argument and output can be a different type

----
Function <String, String> upperCase = s -> s.toUpperCase();
System.out.println(upperCase.apply("convert me to upper"));
----

* Supplier - takes no value, return value
** It represents a function which does not take in any argument but produces a value of type T

----
Supplier<Date> displayDate = ()-> new Date();
System.out.println(displayDate.get());
----

*Streams Methods*

----
Predicate<Integer> getEvenNumber = value -> value%2==0;
Consumer<Integer> displayValue = (value) -> System.out.println(value);
arrli.stream().filter(getEvenNumber).forEach(displayValue);

List <Integer> list = arrli.stream().filter(getEvenNumber).collect(Collectors.toList());

//Map

Predicate<Integer> getEvenNumber = value -> value%2==0;
Consumer<Integer> displayValue = (value) -> System.out.println(value);
Function<Integer, Integer> doubleValue = (value)->value*2;

createList();

//List <Integer> doubleValueList = arrli.stream().map(doubleValue).collect(Collectors.toList());
//doubleValueList.forEach(displayValue);

arrli.stream().map(doubleValue).forEach(displayValue);

//Method Reference

interface IMethodReferenceExample{
    public void methodRef1();
}

interface IMethodReferenceExample_Instance{
    public void methodRef1_Instance();
}

public class MethodReferenceExample {



    public static void methodRef2(){
        System.out.print("methodRef2");
    }

    public void methodRef2_Instance(){
        System.out.print("methodRef2_Instance");
    }

    public static void main(String[] args) {
        //IMethodReferenceExample iMethodReferenceExample = MethodReferenceExample::methodRef2;
        //iMethodReferenceExample.methodRef1();

        MethodReferenceExample methodReferenceExampleObject = new MethodReferenceExample();
        IMethodReferenceExample_Instance iMethodReferenceExample_instance = methodReferenceExampleObject::methodRef2_Instance;
        iMethodReferenceExample_instance.methodRef1_Instance();
    }

}
----

* filter, map, count, sorted, collect
* min, max. It expects a comparator.
* forEach - It takes consumer
* toArray




